library(dendextend)
library(ggplot2)
library(rentrez)
library(plyr); library(dplyr)
#library(microbiome)
library(phyloseq)
library(tidyverse)
library(rioja) # plotting poackages for tabular bubbleplots
library(ggthemes) # additional themes fro ggplot2
library(gridExtra)
#library(ggtern)
library(ggdendro)
library(data.table)
library(vegan)
library(igraph)
library(VSURF)
library(grid)
library(pvclust)
library(shipunov)
library(foreach)
library(patchwork)
library(egg)
library(janitor)
library(RColorBrewer)
library(stringr)
library(svglite)
library(randomcoloR)
#library(drake)
library(ape)
library(ggtree)
library(ggpubr)
library(circlize)
library(missForest)
library(psych)
library(ggvegan)
library(cowplot)


